### ISSUE TITLE
Issue resolved is not available in latest library

### ISSUE THREAD

**Issue by radhakrishnant2s** [Judopay/JudoKit-ReactNative#71]
An issue I raised has been resolved but only when it is tagged in the iOS project, it will be available in React native library

https://github.com/Judopay/JudoKit-iOS/pull/86

**Comment by mpetrenco** [comment]
@radhakrishnant2s you're right. I'm not sure if it's as straightforward as simply tagging the new version, since the iOS SDK has had several released, and we haven't had the chance to look into updating React Native as well.

This has been raised and added as a task in our board, we'll look at it as soon as we can.
Cheers!

**Comment by radhakrishnant2s** [comment]
It is good enough  tag as it will link automatically the native library via pods. Is there any challenges with tagging?

**Comment by mpetrenco** [comment]
@radhakrishnant2s yes, there might be. There have been some significant changes to our iOS SDK that might require us to update the wrapper code as well. We have to do some testing first and see if the new iOS SDK won't affect the RN wrapper code.

**Comment by mpetrenco** [comment]
Please check the new 3.1.0 version of our SDK and see if this issue persists: 
https://www.npmjs.com/package/judokit-react-native

**Comment by mpetrenco** [comment]
Issue was handled at #82
